#!/bin/bash
# Requires scrot for the screenshot, imagemagick to do the blur thing, and i3lock to lock
scrot /tmp/screenshot.png
convert /tmp/screenshot.png -blur 0x5 /tmp/screenshotblur.png
i3lock -i /tmp/screenshotblur.png
if [ ! -z "$1" ]; then
    systemctl suspend
fi
