#!/bin/bash
# Requires scrot for the screenshot, imagemagick to do the blur thing, and i3lock to lock
PHOTODIR=/home/cjc/lockphotos
scrot /tmp/screenshot.png
convert /tmp/screenshot.png -blur 0x9 /tmp/screenshotblur.png
MEPHOTO=$PHOTODIR/$(ls $PHOTODIR | shuf -n 1)
convert /tmp/screenshotblur.png "$MEPHOTO" -gravity SouthEast -composite /tmp/awesomelock.png
i3lock -i /tmp/awesomelock.png
if [ ! -z "$1" ]; then
    systemctl suspend
fi
